#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nnn_T2.dat -c nnn  	-T 
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nGAMMA_T2.dat -c nGAMMA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nEE_T2.dat -c nEE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nEMU_T2.dat -c nEMU  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUE_T2.dat -c nMUE  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUMU_T2.dat -c nMUMU 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nET_T2.dat -c nET   	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nTE_T2.dat -c nTE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nMUT_T2.dat -c nMUT  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nTMU_T2.dat -c nTMU  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nPI0_T2.dat -c nPI0  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EPI_T2.dat -c EPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUPI_T2.dat -c MUPI  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_T2PI_T2.dat -c TPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EKA_T2.dat -c EKA   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUKA_T2.dat -c MUKA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nRHO0_T2.dat -c nRHO0 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_ERHO_T2.dat -c ERHO  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MURHO_T2.dat -c MURHO 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_EKAx_T2.dat -c EKAx  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nKA0x_T2.dat -c nKA0x 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_MUKAx_T2.dat -c MUKAx 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nOMEGA_T2.dat -c nOMEGA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nETA_T2.dat -c nETA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nETAi_T2.dat -c nETAi 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_nPHI_T2.dat -c nPHI  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_FGT -f config/FluxConfig -o Exclusion/FGT/FGT_ECHARM_T2.dat -c ECHARM	-T
