#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

./bin/Plotter -i Exclusion/Couple/nnn_T2.dat -o Exclusion/Plot_Couple/nnn_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nGAMMA_T2.dat -o Exclusion/Plot_Couple/nGAMMA_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nEE_T2.dat -o Exclusion/Plot_Couple/nEE_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/nEMU_T2.dat -o Exclusion/Plot_Couple/nEMU_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/nMUE_T2.dat -o Exclusion/Plot_Couple/nMUE_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nMUMU_T2.dat -o Exclusion/Plot_Couple/nMUMU_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/nET_T2.dat -o Exclusion/Plot_Couple/nET_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nTE_T2.dat -o Exclusion/Plot_Couple/nTE_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/nMUT_T2.dat -o Exclusion/Plot_Couple/nMUT_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nTMU_T2.dat -o Exclusion/Plot_Couple/nTMU_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nPI0_T2.dat -o Exclusion/Plot_Couple/nPI0_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/EPI_T2.dat -o Exclusion/Plot_Couple/EPI_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/MUPI_T2.dat -o Exclusion/Plot_Couple/MUPI_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/TPI_T2.dat -o Exclusion/Plot_Couple/TPI_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/EKA_T2.dat -o Exclusion/Plot_Couple/EKA_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/MUKA_T2.dat -o Exclusion/Plot_Couple/MUKA_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nRHO0_T2.dat -o Exclusion/Plot_Couple/nRHO0_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/ERHO_T2.dat -o Exclusion/Plot_Couple/ERHO_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/MURHO_T2.dat -o Exclusion/Plot_Couple/MURHO_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/EKAx_T2.dat -o Exclusion/Plot_Couple/EKAx_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/nKA0x_T2.dat -o Exclusion/Plot_Couple/nKA0x_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/MUKAx_T2.dat -o Exclusion/Plot_Couple/MUKAx_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nOMEGA_T2.dat -o Exclusion/Plot_Couple/nOMEGA_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nETA_T2.dat -o Exclusion/Plot_Couple/nETA_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nETAi_T2.dat -o Exclusion/Plot_Couple/nETAi_T2.dat -t 2.44
./bin/Plotter -i Exclusion/Couple/nPHI_T2.dat -o Exclusion/Plot_Couple/nPHI_T2.dat -t 2.44
#./bin/Plotter -i Exclusion/Couple/ECHARM_T2.dat -o Exclusion/Plot_Couple/ECHARM_T2.dat -t 2.44
