#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

#./bin/Coupler -A Exclusion/LAr/LAr_nnn_T2.dat -B Exclusion/FGT/FGT_nnn_T2.dat -o Exclusion/Couple/nnn_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nGAMMA_T2.dat -B Exclusion/FGT/FGT_nGAMMA_T2.dat -o Exclusion/Couple/nGAMMA_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nEE_T2.dat -B Exclusion/FGT/FGT_nEE_T2.dat -o Exclusion/Couple/nEE_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nEMU_T2.dat -B Exclusion/FGT/FGT_nEMU_T2.dat -o Exclusion/Couple/nEMU_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nMUE_T2.dat -B Exclusion/FGT/FGT_nMUE_T2.dat -o Exclusion/Couple/nMUE_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nMUMU_T2.dat -B Exclusion/FGT/FGT_nMUMU_T2.dat -o Exclusion/Couple/nMUMU_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nET_T2.dat -B Exclusion/FGT/FGT_nET_T2.dat -o Exclusion/Couple/nET_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nTE_T2.dat -B Exclusion/FGT/FGT_nTE_T2.dat -o Exclusion/Couple/nTE_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_nMUT_T2.dat -B Exclusion/FGT/FGT_nMUT_T2.dat -o Exclusion/Couple/nMUT_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nTMU_T2.dat -B Exclusion/FGT/FGT_nTMU_T2.dat -o Exclusion/Couple/nTMU_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPI0_T2.dat -B Exclusion/FGT/FGT_nPI0_T2.dat -o Exclusion/Couple/nPI0_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EPI_T2.dat -B Exclusion/FGT/FGT_EPI_T2.dat -o Exclusion/Couple/EPI_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUPI_T2.dat -B Exclusion/FGT/FGT_MUPI_T2.dat -o Exclusion/Couple/MUPI_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_T2PI_T2.dat -B Exclusion/FGT/FGT_T2PI_T2.dat -o Exclusion/Couple/TPI_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EKA_T2.dat -B Exclusion/FGT/FGT_EKA_T2.dat -o Exclusion/Couple/EKA_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUKA_T2.dat -B Exclusion/FGT/FGT_MUKA_T2.dat -o Exclusion/Couple/MUKA_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nRHO0_T2.dat -B Exclusion/FGT/FGT_nRHO0_T2.dat -o Exclusion/Couple/nRHO0_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_ERHO_T2.dat -B Exclusion/FGT/FGT_ERHO_T2.dat -o Exclusion/Couple/ERHO_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MURHO_T2.dat -B Exclusion/FGT/FGT_MURHO_T2.dat -o Exclusion/Couple/MURHO_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_EKAx_T2.dat -B Exclusion/FGT/FGT_EKAx_T2.dat -o Exclusion/Couple/EKAx_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nKA0x_T2.dat -B Exclusion/FGT/FGT_nKA0x_T2.dat -o Exclusion/Couple/nKA0x_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_MUKAx_T2.dat -B Exclusion/FGT/FGT_MUKAx_T2.dat -o Exclusion/Couple/MUKAx_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nOMEGA_T2.dat -B Exclusion/FGT/FGT_nOMEGA_T2.dat -o Exclusion/Couple/nOMEGA_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nETA_T2.dat -B Exclusion/FGT/FGT_nETA_T2.dat -o Exclusion/Couple/nETA_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nETAi_T2.dat -B Exclusion/FGT/FGT_nETAi_T2.dat -o Exclusion/Couple/nETAi_T2.dat
./bin/Coupler -A Exclusion/LAr/LAr_nPHI_T2.dat -B Exclusion/FGT/FGT_nPHI_T2.dat -o Exclusion/Couple/nPHI_T2.dat
#./bin/Coupler -A Exclusion/LAr/LAr_ECHARM_T2.dat -B Exclusion/FGT/FGT_ECHARM_T2.dat -o Exclusion/Couple/ECHARM_T2.dat
