#!/bin/bash

cd /mt/home/tboschi/scratch/Supershock

./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nnn_T2.dat -c nnn  	-T 
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nGAMMA_T2.dat -c nGAMMA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nEE_T2.dat -c nEE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nEMU_T2.dat -c nEMU  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUE_T2.dat -c nMUE  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUMU_T2.dat -c nMUMU 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nET_T2.dat -c nET   	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nTE_T2.dat -c nTE   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nMUT_T2.dat -c nMUT  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nTMU_T2.dat -c nTMU  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nPI0_T2.dat -c nPI0  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_EPI_T2.dat -c EPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_MUPI_T2.dat -c MUPI  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_T2PI_T2.dat -c TPI   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_EKA_T2.dat -c EKA   	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_MUKA_T2.dat -c MUKA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nRHO0_T2.dat -c nRHO0 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_ERHO_T2.dat -c ERHO  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_MURHO_T2.dat -c MURHO 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_EKAx_T2.dat -c EKAx  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nKA0x_T2.dat -c nKA0x 	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_MUKAx_T2.dat -c MUKAx 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nOMEGA_T2.dat -c nOMEGA	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nETA_T2.dat -c nETA  	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nETAi_T2.dat -c nETAi 	-T
./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_nPHI_T2.dat -c nPHI  	-T
#./bin/OriginalExclusion -s config/SMConfig -d config/ND_LAr -f config/FluxConfig -o Exclusion/LAr/LAr_ECHARM_T2.dat -c ECHARM	-T
